### ISSUE TITLE
colcon build error

### ISSUE THREAD

**Issue by farbod1277** [intel/ros2_object_analytics#93] opened 2019-07-05 04:19 UTC
Hi I followed the wiki exactly on a fresh installation of Ubuntu 18.04 and when I tried to build OA from source, after running `colcon build --symlink-install` I got the following:

--------------------------------------------------------------------

Starting >>> movidius_ncs_lib
Starting >>> object_analytics_msgs
Starting >>> movidius_ncs_example
Starting >>> movidius_ncs_launch
Finished <<< movidius_ncs_launch [0.37s]                                                                                                      
Finished <<< movidius_ncs_example [0.56s]                                                                   
Finished <<< movidius_ncs_lib [0.66s]                                                                        
Starting >>> movidius_ncs_image
Starting >>> movidius_ncs_stream
Finished <<< movidius_ncs_stream [0.51s]                                                                                                   
Finished <<< movidius_ncs_image [0.53s]
Finished <<< object_analytics_msgs [24.5s]                         
Starting >>> object_analytics_node
Starting >>> object_analytics_rviz
--- stderr: object_analytics_node                                                                           
Release
CMake Error at CMakeLists.txt:48 (find_package):
  By not providing "Findrclcpp_components.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "rclcpp_components", but CMake did not find one.

  Could not find a package configuration file provided by "rclcpp_components"
  with any of the following names:

    rclcpp_componentsConfig.cmake
    rclcpp_components-config.cmake

  Add the installation prefix of "rclcpp_components" to CMAKE_PREFIX_PATH or
  set "rclcpp_components_DIR" to a directory containing one of the above
  files.  If "rclcpp_components" provides a separate development package or
  SDK, be sure it has been installed.

---
Failed   <<< object_analytics_node	[ Exited with code 1 ]
Aborted  <<< object_analytics_rviz                                    

Summary: 6 packages finished [27.8s]
  1 package failed: object_analytics_node
  1 package aborted: object_analytics_rviz
  1 package had stderr output: object_analytics_node

----------------------------------------------------------------

Any help would be appreciated thank you.

My hardware:
Surface Pro 2017 Core i5
NCS2
D435 Camera

**Comment by farbod1277** [comment] 2019-07-05 04:38
Here is a log of everything I did after installing Ubuntu18.04 if that helps:



Log (5/07/2019):
1: https://github.com/intel/ros2_object_analytics:
	1.1: sudo apt-get install ros-crystal-desktop
		>E: Unable to locate package ros-crystal-desktop
		1.1.1: https://index.ros.org/doc/ros2/Installation/Crystal/Linux-Install-Debians/
			1.1.1.1: sudo locale-gen en_US en_US.UTF-8
				 sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
				 export LANG=en_US.UTF-8
			1.1.1.2: sudo apt update && sudo apt install curl gnupg2 lsb-release
				 curl http://repo.ros2.org/repos.key | sudo apt-key add -
			1.1.1.3: sudo sh -c 'echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'
			1.1.1.4: export CHOOSE_ROS_DISTRO=crystal  # or bouncy or ardent
				 sudo apt update
			1.1.1.5: sudo apt install ros-$CHOOSE_ROS_DISTRO-desktop
			1.1.1.6: sudo apt install python3-argcomplete
			1.1.1.7: echo "source /opt/ros/$CHOOSE_ROS_DISTRO/setup.bash" >> ~/.bashrc
				 Close and then open the terminal
	1.2: sudo apt-get install ros-crystal-cv-bridge ros-crystal-object-msgs ros-crystal-image-transport ros-crystal-librealsense2 ros-crystal-realsense-camera-msgs ros-crystal-realsense-ros2-camera
	1.3: sudo apt install git
	1.4: mkdir ~/code
	     cd ~/code
	     git clone https://github.com/movidius/ncsdk
	     git clone https://github.com/movidius/ncappzoo
	     cd ~/code/ncsdk
	     make install
		1.4.1: Close and then open the terminal
	1.5: cd ~/code/ncsdk
	     ln -sf ~/code/ncappzoo /opt/movidius/ncappzoo
	1.6: mkdir ~/ros2_ws/src -p
	     cd ~/ros2_ws/src
	     git clone https://github.com/intel/ros2_intel_movidius_ncs.git
	     cd ~/ros2_ws
	     sudo apt-get install python3-colcon-common-extensions
	     colcon build --symlink-install
	1.7: Plugin NCS2
	1.8: cd /opt/movidius/ncappzoo/caffe/SSD_MobileNet
	     make
	1.9: cp ~/ros2_ws/src/ros2_intel_movidius_ncs/data/labels/* /opt/movidius/ncappzoo/data/ilsvrc12/
	1.10: mkdir ${HOME}/opencv
	      cd ${HOME}/opencv
	      git clone https://github.com/opencv/opencv.git -b 3.3.0
	      git clone https://github.com/opencv/opencv_contrib.git -b 3.3.0
	      mkdir opencv/build -p
	      cd opencv/build
	1.11: sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
	1.12: cmake -D OPENCV_EXTRA_MODULES_PATH=${HOME}/opencv/opencv_contrib/modules -D CMAKE_INSTALL_PREFIX=/usr/local -D BUILD_opencv_cnn_3dobj=OFF ..
	      make -j8
	      sudo make install
              sudo ldconfig
	      sudo apt-get install liblz4-dev
	1.13: sudo apt-get install ros-crystal-object-analytics-msgs ros-crystal-object-analytics-node ros-crystal-object-analytics-rviz
	1.14: mkdir ~/ros2_ws/src -p
	      cd ~/ros2_ws/src
	      git clone https://github.com/intel/ros2_object_analytics.git -b devel
	1.15: cd ~/ros2_ws
	      source /opt/ros/crystal/setup.bash
	      colcon build --symlink-install
		>E:
			Starting >>> movidius_ncs_lib
			Starting >>> object_analytics_msgs
			Starting >>> movidius_ncs_example
			Starting >>> movidius_ncs_launch
			Finished <<< movidius_ncs_launch [0.37s]                                                                                                      
			Finished <<< movidius_ncs_example [0.56s]                                                                   
			Finished <<< movidius_ncs_lib [0.66s]                                                                        
			Starting >>> movidius_ncs_image
			Starting >>> movidius_ncs_stream
			Finished <<< movidius_ncs_stream [0.51s]                                                                                                   
			Finished <<< movidius_ncs_image [0.53s]
			Finished <<< object_analytics_msgs [24.5s]                         
			Starting >>> object_analytics_node
			Starting >>> object_analytics_rviz
			--- stderr: object_analytics_node                                                                           
			Release
			CMake Error at CMakeLists.txt:48 (find_package):
			  By not providing "Findrclcpp_components.cmake" in CMAKE_MODULE_PATH this
			  project has asked CMake to find a package configuration file provided by
			  "rclcpp_components", but CMake did not find one.

			  Could not find a package configuration file provided by "rclcpp_components"
			  with any of the following names:

			    rclcpp_componentsConfig.cmake
			    rclcpp_components-config.cmake

			  Add the installation prefix of "rclcpp_components" to CMAKE_PREFIX_PATH or
			  set "rclcpp_components_DIR" to a directory containing one of the above
			  files.  If "rclcpp_components" provides a separate development package or
			  SDK, be sure it has been installed.


			---
			Failed   <<< object_analytics_node	[ Exited with code 1 ]
			Aborted  <<< object_analytics_rviz                                    

			Summary: 6 packages finished [27.8s]
			  1 package failed: object_analytics_node
			  1 package aborted: object_analytics_rviz
			  1 package had stderr output: object_analytics_node

**Comment by challen-zhou** [comment] 2019-07-05 07:55
@farbod1277 , you need to use latest ROS2 dashing core with latest code of this module. If you want to build with crystal, you can check the tag 0.5.0-crystal

**Comment by farbod1277** [comment] 2019-07-05 09:09
@challen-zhou Thank you for your response. I built on tag 0.5.0_crystal and this was the output (succeeeded with some warnings):

-------------------------------------------

Starting >>> movidius_ncs_lib
Starting >>> object_analytics_msgs
Starting >>> movidius_ncs_example
Starting >>> movidius_ncs_launch
Finished <<< movidius_ncs_launch [0.65s]                                                                                                      
Finished <<< movidius_ncs_lib [0.99s]                                                                            
Starting >>> movidius_ncs_image
Starting >>> movidius_ncs_stream
Finished <<< movidius_ncs_example [1.00s]                                                                            
Finished <<< movidius_ncs_image [0.77s]                                                                                                    
Finished <<< movidius_ncs_stream [0.83s]                                                                        
Finished <<< object_analytics_msgs [7.78s]                       
Starting >>> object_analytics_node
Starting >>> object_analytics_rviz
--- stderr: object_analytics_rviz                                                                                        
/home/farbod/ros2_ws/src/ros2_object_analytics/object_analytics_rviz/src/marker_publisher.cpp: In member function ‘visualization_msgs::msg::Marker MarkerPublisher::createNameIDMarker(std_msgs::msg::Header, geometry_msgs::msg::Point, geometry_msgs::msg::Point, std::__cxx11::string&, int, int&)’:
/home/farbod/ros2_ws/src/ros2_object_analytics/object_analytics_rviz/src/marker_publisher.cpp:254:29: warning: unused parameter ‘obj_id’ [-Wunused-parameter]
     std::string & name, int obj_id, int & marker_id)
                             ^~~~~~
/usr/bin/ld: warning: libopencv_imgcodecs.so.3.2, needed by /opt/ros/crystal/lib/libcv_bridge.so, may conflict with libopencv_imgcodecs.so.3.3
/usr/bin/ld: warning: libopencv_imgproc.so.3.2, needed by /opt/ros/crystal/lib/libcv_bridge.so, may conflict with libopencv_imgproc.so.3.3
/usr/bin/ld: warning: libopencv_core.so.3.2, needed by /opt/ros/crystal/lib/libcv_bridge.so, may conflict with libopencv_core.so.3.3
---
Finished <<< object_analytics_rviz [17.6s]
[Processing: object_analytics_node]                             
[Processing: object_analytics_node]                                       
[Processing: object_analytics_node]                                       
[Processing: object_analytics_node]                                       
[Processing: object_analytics_node]                                       
[Processing: object_analytics_node]                                       
--- stderr: object_analytics_node                                            
** WARNING ** io features related to ensenso will be disabled
** WARNING ** io features related to davidSDK will be disabled
** WARNING ** io features related to dssdk will be disabled
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
** WARNING ** io features related to libusb-1.0 will be disabled
** WARNING ** 2d features related to ensenso will be disabled
** WARNING ** 2d features related to davidSDK will be disabled
** WARNING ** 2d features related to dssdk will be disabled
** WARNING ** 2d features related to pcap will be disabled
** WARNING ** 2d features related to png will be disabled
** WARNING ** 2d features related to libusb-1.0 will be disabled
** WARNING ** io features related to ensenso will be disabled
** WARNING ** io features related to davidSDK will be disabled
** WARNING ** io features related to dssdk will be disabled
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
** WARNING ** io features related to libusb-1.0 will be disabled
/home/farbod/ros2_ws/src/ros2_object_analytics/object_analytics_node/tests/unittest_segmenter.cpp: In member function ‘virtual void Algo::segment(const ConstPtr&, std::vector<pcl::PointIndices>&)’:
/home/farbod/ros2_ws/src/ros2_object_analytics/object_analytics_node/tests/unittest_segmenter.cpp:41:54: warning: unused parameter ‘cloud’ [-Wunused-parameter]
     const pcl::PointCloud<pcl::PointXYZ>::ConstPtr & cloud,
                                                      ^~~~~
---
Finished <<< object_analytics_node [3min 32s]

Summary: 8 packages finished [3min 40s]
  2 packages had stderr output: object_analytics_node object_analytics_rviz

--------------------------------------------------------------------

But when I try to run the demo I get this:

----------------------------------------------------------------------

[INFO] [launch]: process[realsense_ros2_camera-1]: started with pid [16055]
[INFO] [launch]: process[api_composition-2]: started with pid [16056]
[INFO] [launch]: process[api_composition_cli-3]: started with pid [16057]
[INFO] [launch]: process[api_composition_cli-4]: started with pid [16058]
[INFO] [launch]: process[object_analytics_node-5]: started with pid [16060]
[INFO] [launch]: process[image_publisher-6]: started with pid [16072]
[INFO] [launch]: process[marker_publisher-7]: started with pid [16079]
[INFO] [launch]: process[rviz2-8]: started with pid [16088]
[INFO] [object_analytics_node]: Load library /home/farbod/ros2_ws/install/object_analytics_node/lib/libsplitter_component.so
[INFO] [object_analytics_node]: Instantiate class object_analytics_node::splitter::SplitterNode
[INFO] [object_analytics_node]: Load library /home/farbod/ros2_ws/install/object_analytics_node/lib/libsegmenter_component.so
[INFO] [api_composition_cli]: Sending request...
[INFO] [api_composition_cli]: Waiting for response...
[ERROR] [api_composition]: Could not find requested resource in ament index
[INFO] [api_composition_cli]: Sending request...
[INFO] [api_composition_cli]: Waiting for response...
[INFO] [marker_publisher]: Start MarkerPublisher ...
[INFO] [api_composition]: Load library /home/farbod/ros2_ws/install/movidius_ncs_stream/lib/libmovidius_ncs_stream.so
[INFO] [object_analytics_node]: Instantiate class object_analytics_node::segmenter::SegmenterNode
[INFO] [api_composition]: Instantiate class movidius_ncs_stream::NCSComposition
[DEBUG] [movidius_ncs_lib]: NCSImpl get parameters
[INFO] [movidius_ncs_lib]: use device_index = 0
[INFO] [movidius_ncs_lib]: use log_level = 0
[INFO] [movidius_ncs_lib]: use graph_file_path = /opt/movidius/ncappzoo/caffe/SSD_MobileNet/graph
[INFO] [movidius_ncs_lib]: use category_file_path = /opt/movidius/ncappzoo/data/ilsvrc12/voc21.txt
[INFO] [movidius_ncs_lib]: use cnn_type_ = mobilenetssd
[INFO] [movidius_ncs_lib]: use network_dimension = 300
[INFO] [movidius_ncs_lib]: use channel1_mean = 127.5
[INFO] [movidius_ncs_lib]: use channel2_mean = 127.5
[INFO] [movidius_ncs_lib]: use channel3_mean = 127.5
[INFO] [movidius_ncs_lib]: use top_n = 1
[INFO] [movidius_ncs_lib]: use scale = 0.007843
[ERROR] [movidius_ncs_stream]: Error: there is no device at the given index or name
[INFO] [api_composition_cli]: Result of load_node: success = true
[INFO] [object_analytics_node]: Load library /home/farbod/ros2_ws/install/object_analytics_node/lib/libmoving_component.so
[INFO] [launch]: process[api_composition_cli-4]: process has finished cleanly
[INFO] [object_analytics_node]: Instantiate class object_analytics_node::movement::MovementNode
[INFO] [image_publisher]: Start ImagePublisher ...
[INFO] [MovementNode]: ...Creating Moving Objects buffer...
[INFO] [launch]: process[api_composition-2]: process has finished cleanly
[INFO] [RealSenseCameraNode]: RealSense ROS v2. 0.1
[INFO] [RealSenseCameraNode]: Running with LibRealSense v2.16.5
[INFO] [RealSenseCameraNode]: getParameters...
[INFO] [RealSenseCameraNode]: setupDevice...
[INFO] [RealSenseCameraNode]: Device Name: Intel RealSense D435
[INFO] [RealSenseCameraNode]: Device Serial No: 801312070095
[INFO] [RealSenseCameraNode]: Device FW version: 05.10.03.00
[INFO] [RealSenseCameraNode]: Device Product ID: 0B07
[INFO] [RealSenseCameraNode]: Sync Mode: On
[INFO] [RealSenseCameraNode]: Device Sensors: 
[INFO] [RealSenseCameraNode]: Stereo Module was found.
[INFO] [RealSenseCameraNode]: RGB Camera was found.
[INFO] [RealSenseCameraNode]: Fisheye sensor isn't supported by current device! -- Skipping...
[INFO] [RealSenseCameraNode]: Gyro sensor isn't supported by current device! -- Skipping...
[INFO] [RealSenseCameraNode]: Accel sensor isn't supported by current device! -- Skipping...
[INFO] [RealSenseCameraNode]: setupPublishers...
[INFO] [RealSenseCameraNode]: setupStreams...
[INFO] [RealSenseCameraNode]: depth stream is enabled - width: 640, height: 480, fps: 30
[INFO] [RealSenseCameraNode]: infra1 stream is enabled - width: 640, height: 480, fps: 30
[INFO] [RealSenseCameraNode]: infra2 stream is enabled - width: 640, height: 480, fps: 30
[INFO] [RealSenseCameraNode]: color stream is enabled - width: 640, height: 480, fps: 30
[INFO] [api_composition_cli]: Response not available, waiting again...
[INFO] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [rviz2]: OpenGl version: 3 (GLSL 1.3)
[INFO] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [api_composition_cli]: Response not available, waiting again...
[INFO] [RealSenseCameraNode]: publishStaticTransforms...
[INFO] [RealSenseCameraNode]: RealSense Node Is Up!
[INFO] [api_composition_cli]: Response not available, waiting again...
[INFO] [api_composition_cli]: Response not available, waiting again...
[INFO] [api_composition_cli]: Response not available, waiting again...
[INFO] [api_composition_cli]: Response not available, waiting again...
[INFO] [api_composition_cli]: Response not available, waiting again...
[INFO] [api_composition_cli]: Response not available, waiting again...


---------------------------------------------------------------------

What could be wrong with it? Thanks again :)

**Comment by farbod1277** [comment] 2019-07-06 06:03
@challen-zhou I also tried again with ros-dashing this time but this time movidius_ncs_stream doesn't build. Output:

------------------------------------------------------------

Starting >>> movidius_ncs_lib
Starting >>> movidius_ncs_example
Starting >>> movidius_ncs_launch
Finished <<< movidius_ncs_launch [0.68s]                                                                                                      
Finished <<< movidius_ncs_lib [13.2s]                                                                              
Starting >>> movidius_ncs_image
Starting >>> movidius_ncs_stream
--- stderr: movidius_ncs_stream                                                                                                           
CMake Error at CMakeLists.txt:44 (rclcpp_register_node_plugins):
  Unknown CMake command "rclcpp_register_node_plugins".


---
Failed   <<< movidius_ncs_stream	[ Exited with code 1 ]
Aborted  <<< movidius_ncs_example                                                                                        
Aborted  <<< movidius_ncs_image                                    

Summary: 2 packages finished [16.2s]
  1 package failed: movidius_ncs_stream
  2 packages aborted: movidius_ncs_example movidius_ncs_image
  1 package had stderr output: movidius_ncs_stream

-----------------------------------------------------

Is there a stable version of this package which works with all the other dependent packages? Thank you

**Comment by challen-zhou** [comment] 2019-07-08 01:09
@farbod1277 , you may got some hardware issue since i saw "[ERROR] [movidius_ncs_stream]: Error: there is no device at the given index or name" in your log, we got some similar issues before, it may caused by the hardware ID confliction between NCS1 and RealSense. 
Suggest you can turn to use devel branch in this module and use openvino as detection backend.

For stable version, you can try https://github.com/intel/robot_devkit, which integrate all the necessary modules include this OA module and we have regression every week, but it was using the latest ROS2 core. The default detection backend is openvino-NCS2, you can also hack to use GPU for detection if you do not have NCS2 on hand.

**Comment by farbod1277** [comment] 2019-08-13 01:54
@challen-zhou Thank you! I will try again with robot_devkit. Hopefully I can get a stable version running.

**Comment by farbod1277** [comment] 2019-08-15 12:37
@challen-zhou I tried robot_devkit and there is an issue with numpy version. There is an open issue on their github repo.

**Comment by challen-zhou** [comment] 2019-08-16 02:06
@farbod1277 , thanks for the feedback! I think they would check and help to resolve the issue.

Would you mind to close this issue ticket and create new one if you need further support?

**Closed** 2019-08-16 10:00 UTC
