### ISSUE TITLE
when I compiled OA in ros2,I got some errors

### ISSUE THREAD

**Issue by qingmingjie** [intel/ros2_object_analytics#5] opened 2018-06-11 05:40 UTC
ament build

+++ Building 'movidius_ncs_example'
...
In file included from /home/qmj/obj2_ws/src/ros2_intel_movidius_ncs/movidius_ncs_example/src/image_classification.cpp:16:
/home/qmj/ros2_ws/install/include/rclcpp/parameter.hpp:65:12: error: expected primary-expression before ‘auto’
   decltype(auto)
            ^
/home/qmj/ros2_ws/install/include/rclcpp/parameter.hpp:65:12: error: expected ‘)’ before ‘auto’

**Comment by Peter9606** [comment] 2018-06-11 05:54
@qingmingjie what compiler do you use? which version is it ?

**Comment by qingmingjie** [comment] 2018-06-11 06:02
Gcc 5.4.0 20160609

**Comment by qingmingjie** [comment] 2018-06-11 07:45
@Peter9606 gcc-5.4.0

**Comment by chaoli2** [comment] 2018-06-11 08:37
@qingmingjie @Peter9606 This issue is caused by the wrong CMAKE_CXX_FLAGS. We've submitted [PR ](https://github.com/intel/ros2_intel_movidius_ncs/pull/17) to fix this issue. It will be merged after validation.

**Comment by yechun1** [comment] 2018-06-12 02:40
@qingmingjie this is 'movidius_ncs_example' build issue, please report to[ ros2_intel_movidius_ncs](https://github.com/intel/ros2_intel_movidius_ncs). thanks.

**Comment by yechun1** [comment] 2018-06-12 02:40
As this issue is ros2_intel_movidius_ncs, I'll close it.

**Closed** 2018-06-12 02:41 UTC

**Comment by qingmingjie** [comment] 2018-06-12 02:45
ok
